### ISSUE TITLE
Error if add-on is active but integration doesn't exist

### ISSUE THREAD

**Issue by rvdsteege** [wp-pay-gateways/payvision#2]
If the integration does not exist anymore in the main plugin, this gateway add-on results in a fatal error.

```
Fatal error: Uncaught Error: Class 'Pronamic\WordPress\Pay\Gateways\Payvision\Integration' not found in /wp-content/plugins/pronamic-pay-payvision/pronamic-pay-payvision.php on line 31
```

We might want to look into using the Jetpack autoloader:
- https://github.com/Automattic/jetpack/tree/trunk/projects/packages/autoloader

**Comment by remcotolsma** [comment]
A quick dirty solution in the Pronamic Pay plugin?

```php
deactivate_plugins( 'pronamic-pay-payvision/pronamic-pay-payvision.php' );
``` 

Won't work if a user installed the add-on in for example `pronamic-pay-payvision-addon/pronamic-pay-payvision.php`.

Otherwise we have to launch an update for this plugin.

https://github.com/pronamic/wp-pronamic-pay-payvision/blob/5d3df4ac0ab8c8c2361dcf9f2a50ab8989f571a4/pronamic-pay-payvision.php#L28-L51

https://github.com/pronamic/wp-pronamic-pay/blob/4b879cefeacdccc5be1564d9dbf788a2a970d8fa/pronamic-ideal.php#L64-L79

_In `develop` we already removed Payvision from the updater._

**Comment by rvdsteege** [comment]
👍

**Comment by remcotolsma** [comment]
Fixed in https://github.com/pronamic/wp-pronamic-pay-payvision/releases/tag/3.2.0 and https://github.com/pronamic/wp-pronamic-pay/commit/154bdb2a3c26ec99c7180c5576490908364496a1.
